### ISSUE TITLE
We need to split this gem

### ISSUE THREAD

**Issue by akzhan** [maca/inline-style#5]
We need to split this gem to be usable not from Rack applications (especially CLI mail notifiers).

May be <b>inline-style-core</b> gem without rack, active support, mail and pluggable dependencies, also without Gemfiles, and <b>inline-style</b> gem that provides full functionality.

**Comment by akzhan** [comment]
this is wanted because I look for nokogiri-based inline styler for git-commit-notifier project.

This project must not depend on rack (it is not web-related) nor bundler, of course (to be simple for installation).

**Comment by eric1234** [comment]
inline-style is not dependent on rack. The rack module and mail interceptor are just convenience features. To use outside of Rack or a mail interceptor just follow the USAGE section in the README. I don't believe they are even run-time dependencies.

**Comment by akzhan** [comment]
Oops, Yes, it is. I looked into Gemfile not gemspec :)

I will try this gem :)
