### ISSUE TITLE
Undefined InlineStyle constant when requiring classes

### ISSUE THREAD

**Issue by 0xradical** [maca/inline-style#6]
This error is raised when I run v0.4.8:
  ..gems/inline-style-0.4.8/lib/inline-style/selector.rb:4: uninitialized constant InlineStyle (NameError)

I guess it's because you open the class InlineStyle::Selector without InlineStyle itself being defined , maybe you should just open the class before the line require 'inline_style/selector' (class InlineStyle; end)

**Comment by maca** [comment]
Thanks for catching it, has been fixed in 0.4.9. 
0.4.8 has been yanked from gemcutter.
